apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: xs08mubij-nodejs 
  janus-idp.io/tekton: xs08mubij-nodejs
  backstage.io/kubernetes-id: xs08mubij-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xs08mubij-nodejs
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml